name: Build to AWS ECR
on: 
  push

jobs:
  login-to-aws:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

  build-and-push-pub-ecr:
    runs-on: ubuntu-latest
    needs: login-to-aws
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Debug - List Files
        run: ls -la
      
      - name: Login to AWS ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t kannel .
          docker tag kannel:latest public.ecr.aws/h8o8x8t1/kannel:v3
          docker push public.ecr.aws/h8o8x8t1/kannel:v3
